export { default as ArrowRightColorIcon } from './ArrowRightColorIcon'
export { default as CafeteriaIconColor } from './CafeteriaIconColor'
export { default as EodiroLogo } from './EodiroLogo'
export { default as LecturesIconColor } from './LecturesIconColor'
export { default as OpensourceIconColor } from './OpensourceIconColor'
export { default as SquareIconColor } from './SquareIconColor'
export { default as ThreeDotsVerticalColorIcon } from './ThreeDotsVerticalColorIcon'
export { default as VacantIconColor } from './VacantIconColor'
